* концепт распределённой сети, состоящей из страниц и представленной в виде большой карты
** как это с первого взгляда
   Пользователь получает интерфейс, в виде карты с приближением-отдалением, подобно тому как работают большинство
   современных картографических сервисов вроде maps.google.
   Но вместо географической карты есть поверхность, на которую нанесены различные графические элементы:
   + текст
   + изображения
   + различные медиа(звук, видео)
   + любой графический элемент, типа виджет
   Пользователь наносит такие элементы на часть карты как на обычный холст. Но суть в том, что рядом другой наносит
   другие элементы. То есть действие похоже на общее рисование на одном большом холсте. С той разницей, что
   всегда можно вставить новые элементы между другими, даже если между ними нет места. Это похоже на то, как 
   высыпать крупу на стол, а потом всыпать ещё немного крупы в середину и разровнять. Крупа просто распределится
   по столу.
   Так люди сообща могут создавать и структурировать информацию совместно. Например так можно сделать фотоальбом,
   а можно несколько фотоальбомов знакомых людей. А можно несколько страничек знакомых между собой людей и рядом
   их фотоальбомы. Когда же человек работает с такой поверхностью, он использует зрительную память чтобы запоминать
   что где находится, ему так ориентировать куда проще чем с помощью адресов. Если же нужно запомнить несколько
   нужных мест на такой карте, то он просто устанавливает туда флажки с подписями и они всегда перед ним.

** пользовательский интерфейс
   + безмерный холст
   + кнопки приближения и отдаления
   + каталог элементов для добавления на холст, возможно и не каталонг? а просто то ли ещё один холст то ли 
     на этом в каком-то месте.
     Главное чтобы они были расположены визуально, не перекрывая друг друга и их можно было перетаскивать.

** как устроено
   + хранение
     Холст эластичный, поэтому не используется абсолютная адресация по x,y. Вместо этого холст реализован как
     распределённая сетка и элементы вставляются путём добавление клеток в какое-то место сетки. Части сетки
     хранятся в сараях(caravan). Все элементы также хранятся в сараях, по возможности там же где фрагменты сетки
     (ячейки), в которых находятся.

  + отображение.
    При максимальном приближении это просто холст с графическими элементами, который можно прокручивать в
    любом направлении и элементы которого будут динамически подгружаться.
    
    При уменьшении используется механизм линзы и её расстояния. То есть мы  имеем некоторое окно, допустим
    1024*800 и некоторый прямоугольник на поверхности, допустим 2000*2000. Что значит 4х кратное уменьшение.
    В таком случае каждый элемент, содержащийся на этой поверхности отдаст в 4е раза меньше пикселей, то есть
    свою миниатюру. При б'ольшем отдалении отдаст ещё меньше и тд до нуля. В какой-то момент элемент не будет
    отдавать никаких пикселей, однако тот один последний пиксель будет хранится в некотором слое, который
    в свою очередь также при дальнейшем уменьшении будет отдавать свои миниатюры всё меньше и меньше.
    
    В результате образуются виртуальные слои, по одному на единицу уменьшения. Постепенно уменьшаясь от 
    2000*2000 они доходят до 1024*800. Если посмотреть как бы сбоку, это будет треугольник или пирамида.
    Каждый такой слой формируется динамически теми, в чьих сараях находятся элементы из первоначального слоя,
    то есть той части сетки, которая просматривается. Также они формируются и просматривающим.

    Таким образом никакого хранения плиток для разных режимов нет, хотя кеширование возможно и поощрается.
